pgmoneta/pgmoneta

doc/CONFIGURATION.md
doc/GETTING_STARTED.md
doc/tutorial/01_install.md
src/include/pgmoneta.h
src/libpgmoneta/configuration.c
src/libpgmoneta/wf_local.c
src/libpgmoneta/workflow.c

Adding a workflow node for the local storage engine.

Adding a local storage workflow

---

.github/workflows/ci.yml
CMakeLists.txt
README.md
cmake/FindLibssh.cmake
doc/CONFIGURATION.md
doc/SSH.md
pgmoneta.spec
src/CMakeLists.txt
src/include/pgmoneta.h
src/include/storage.h
src/include/utils.h
src/include/workflow.h
src/libpgmoneta/configuration.c
src/libpgmoneta/se_local.c
src/libpgmoneta/se_ssh.c
src/libpgmoneta/utils.c
src/libpgmoneta/workflow.c

Creating a backup for a remote server using libssh

[pgmoneta#77] Adding a remote backup

---

AUTHORS

Adding my contact name and email to the authors.

Add an author

---

AUTHORS
CONTRIBUTING.md
README.md
doc/tutorial/01_install.md

Some tips to help setting up the environment, as discussed [here](https://github.com/pgmoneta/pgmoneta/discussions/106)

Add more tips for setting up environment

---

doc/CONFIGURATION.md
doc/tutorial/09_retention.md
src/include/pgmoneta.h
src/libpgmoneta/configuration.c
src/libpgmoneta/lz4_compression.c
src/libpgmoneta/management.c
src/libpgmoneta/prometheus.c
src/libpgmoneta/wf_retain.c

This PR is to address #115 , but without using array.
@jesperpedersen please note that I currently only changed the parsing part in `configuration.c`, if this is better then I'll make changes to the rest.

Retention configuration extension

---

src/include/message.h
src/include/pgmoneta.h
src/include/server.h
src/libpgmoneta/message.c
src/libpgmoneta/server.c

Created some functions to get server version, and for more, since now people can create whatever query message with the query they want

[#123]Common functionalities for querying server version

---

.github/workflows/ci.yml
CMakeLists.txt
CONTRIBUTING.md
README.md
cmake/FindCJSON.cmake
pgmoneta.spec
src/CMakeLists.txt
src/include/manifest.h
src/libpgmoneta/manifest.c
src/libpgmoneta/message.c

Used cJSON to parse the manifest.

Verify base backup with received manifest

---

contrib/grafana/dashboard.json
src/include/management.h
src/include/pgmoneta.h
src/libpgmoneta/archive.c
src/libpgmoneta/backup.c
src/libpgmoneta/management.c
src/libpgmoneta/prometheus.c
src/libpgmoneta/restore.c
src/main.c

[pgmoneta#133] add client operations metrics and design dashboard for them

---

src/libpgmoneta/configuration.c
src/libpgmoneta/wal.c

Hi, 
I realized that there's a bit flaw in my previous patch, thanks to the reminder of #201. This is a small fix to address that. Sorry about the trouble.

[#187]copy cur_timeline & initialize timeline_history

---

AUTHORS
src/include/pgmoneta.h
src/libpgmoneta/configuration.c
src/libpgmoneta/prometheus.c
src/libpgmoneta/wal.c

Added new field `current_wal_filename` to struct `server`, which is then exposed to the prometheus metrics.
Closes #200.

[#200] Expose current streaming WAL filename to Prometheus interface

---

AUTHORS
src/main.c

Assign a value to slot_status in the init_replication_slots function in the main.c file.

[#209] fix issue uniitialized

---

doc/DEVELOPERS.md
doc/PR_GUIDE.md
pgmoneta.spec

Follow these steps to install pgmoneta.

[#219] Install pgmoneta

---

doc/DEVELOPERS.md

Changed the code for switching to the 'postgres' user

Update DEVELOPERS.md Issue#233

---

contrib/shell_comp/pgmoneta_comp.bash
contrib/shell_comp/pgmoneta_comp.zsh
doc/ARCHITECTURE.md
doc/CLI.md
doc/DEVELOPERS.md
doc/GETTING_STARTED.md
doc/man/pgmoneta-admin.1.rst
doc/man/pgmoneta-cli.1.rst
doc/tutorial/01_install.md
doc/tutorial/03_remote_management.md
src/CMakeLists.txt
src/admin.c
src/cli.c
src/include/pgmoneta.h
src/include/utils.h
src/libpgmoneta/utils.c

Porting CLI infrastructure from pgagroal to pgmoneta

[#205] Porting command line parsing infrastructure

---

doc/CONFIGURATION.md
src/include/message.h
src/include/network.h
src/include/pgmoneta.h
src/libpgmoneta/configuration.c
src/libpgmoneta/message.c
src/libpgmoneta/network.c
src/libpgmoneta/wal.c
src/libpgmoneta/wf_backup.c

[#196] Network rate limit for backup

---

src/include/security.h
src/libpgmoneta/manifest.c
src/libpgmoneta/se_s3.c
src/libpgmoneta/se_ssh.c
src/libpgmoneta/security.c
src/libpgmoneta/wf_sha256.c

[#266] Add functions for SHA cheksums for a file

---

src/include/json.h
src/libpgmoneta/json.c

[#331] Add missing JSON function implementations

---

doc/CONFIGURATION.md
doc/man/pgmoneta.conf.5.rst
doc/manual/02-installation.md
doc/manual/99-references.md
doc/manual/user-02-configuration.md
doc/tutorial/15_extra.md
pgmoneta.spec
src/include/extension.h
src/include/info.h
src/include/message.h
src/include/pgmoneta.h
src/include/utils.h
src/include/workflow.h
src/libpgmoneta/backup.c
src/libpgmoneta/configuration.c
src/libpgmoneta/extension.c
src/libpgmoneta/info.c
src/libpgmoneta/management.c
src/libpgmoneta/message.c
src/libpgmoneta/utils.c
src/libpgmoneta/wf_extra.c
src/libpgmoneta/workflow.c

Currently, we can retrieve the byte content of a file and list all file paths under a directory.
Is there already a function to transfer the file from the server to the backend in `pgmoneta`, or how do we handle file transfers in `pgmoneta`? 
I am trying to transfer the file to the backend now.

[#328] Get extra files

---

src/cli.c
src/include/utils.h
src/libpgmoneta/utils.c

Translations for :-
- Command
- Output Format
- Valid field
- Compression field
- Encryption field
@jesperpedersen PTAL

[#366] client side translation of numeric values

---

src/cli.c

[#436] Allow file based commands to run without a server

---

src/admin.c

[#460] Proper error checking in master_key()

---

AUTHORS
doc/manual/97-acknowledgement.md
doc/manual/advanced/97-acknowledgement.md
src/include/security.h
src/libpgmoneta/security.c
src/libpgmoneta/server.c

Utilized Startup packets ('S' B) to set server version. (#498)

Use startup packets to set server version

---

src/include/walfile/relpath.h
src/libpgmoneta/walfile/relpath.c

- Add input validation for fork numbers to prevent invalid access
- Improve memory management with proper cleanup
- Add version bound constants for better maintainability
- Optimize fork names lookup with static const array
- Add proper error codes for better error reporting
- Added `is_valid_fork_number()` validation helper
- Added `MIN_PG_VERSION` and `MAX_PG_VERSION` constants
- Enhanced error reporting with `errno` codes
- Optimized string handling with static arrays
- Added memory allocation failure checks

feat: Enhance relpath error handling and validation

---

.github/workflows/ci.yml
CMakeLists.txt
src/libpgmoneta/security.c
src/libpgmoneta/utils.c
test/testsuite.sh

[#555] fix: macos compatibility

---

.github/workflows/ci.yml
doc/manual/dev-06-wal.md

https://github.com/pgmoneta/pgmoneta/issues/568
Also Fixed a LaTeX syntax error caused by placing a Markdown link inside backticks (``), which prevented PDF generation.

[#568] Improve CI Pipeline for pgmoneta

---

src/cli.c

Implement #567 
This PR enable CLI running `encrypt/compress/decrypt/decompress` commands without `pgmoneta.conf` or `-c`
1. Add `is_local_command` check to determine if the command should run locally
2. Default to ZSTD when config is not provided for local compression

[#567] encrypt/compress/decrypt/decompress without config

---

AUTHORS
doc/CONFIGURATION.md
doc/manual/97-acknowledgement.md
doc/manual/advanced/97-acknowledgement.md
src/cli.c
src/include/utils.h
src/libpgmoneta/configuration.c
src/libpgmoneta/logging.c
src/libpgmoneta/utils.c

[#575] file logging: support environment variables

---

doc/manual/advanced/05-backup.md
src/include/security.h
src/include/workflow_funcs.h
src/libpgmoneta/backup.c
src/libpgmoneta/keep.c
src/libpgmoneta/wf_sha512.c
src/libpgmoneta/workflow.c

[#612] Create backup.sha512 for entire backup

---

doc/manual/dev-08-wal.md
src/include/utils.h
src/include/walfile.h
src/include/walfile/wal_reader.h
src/libpgmoneta/utils.c
src/libpgmoneta/walfile.c
src/libpgmoneta/walfile/wal_reader.c
src/walinfo.c

[#414] Reading Wal files from a directory

---

doc/manual/advanced/hi/04-configuration.md
doc/manual/advanced/hi/05-backup.md
doc/manual/advanced/hi/12-docker.md

Translated the advanced manual documentation for Docker in Hindi.
@jesperpedersen PTAL

[#637] Hindi: Verification and Docker

---

src/libpgmoneta/verify.c

[#640]Fix Hash validation

---

doc/CONFIGURATION.md
doc/tutorial/13_hot_standby.md
src/include/pgmoneta.h
src/include/utils.h
src/libpgmoneta/configuration.c
src/libpgmoneta/prometheus.c
src/libpgmoneta/status.c
src/libpgmoneta/utils.c
src/libpgmoneta/wf_delete.c
src/libpgmoneta/wf_hot_standby.c
src/libpgmoneta/wf_retention.c

hot_standby now supports multiple directories.
resolves #547

[#547]Support Multiple Hot Standby Directories

---

doc/PROMETHEUS.md
doc/manual/user-11-prometheus.md
src/include/extension.h
src/include/pgmoneta.h
src/libpgmoneta/extension.c
src/libpgmoneta/prometheus.c
src/libpgmoneta/server.c

Addressing #669. PTAL @jesperpedersen

Detect extension on startup

---

src/libpgmoneta/backup.c
src/libpgmoneta/info.c
src/libpgmoneta/wf_backup.c
src/libpgmoneta/wf_link.c
src/libpgmoneta/wf_manifest.c
src/libpgmoneta/workflow.c

- Fixed bugs in load/store backup #579 
- Addresses bug in #656  (refer discussion - #683)

[#683] Memory leaks in backup

---

src/cli.c

[#693] Use type-checked section extraction with pgmoneta_json_get_typed

---

src/libpgmoneta/walfile/wal_reader.c

Resolves #688 
This patch should fix the calculation of the offset of the first record after the long header correctly when there are remaining bytes from the previous segment.

[#688] Fixed the first record's offset calculation

---

src/libpgmoneta/walfile/wal_reader.c

Resolves #668 
There was a solution where I can save the offset of the record then compute the position of the next record and then move the point 3 fields that are before `lsn` so that we can allocate it on the fly but I thought this solution would be very error-prone and probably complex to debug or maintain and also I will have to handle records spanning multiple pages where I will have to calculate the sizes of page headers in between to seek to the record start. So I decided to go with this solution.
PTAL @jesperpedersen

[#668] Compute next_lsn in decoded_xlog_record

---

test/testcases/pgmoneta_test_3.c

`accept` was running into race issues.  This uses `select` with some break mechanism and fixes the issues. Addressing #706

Use select for HTTP test suite

---

src/include/server.h
src/libpgmoneta/server.c

Feature #709 
This patch contains the API to fetch the binary content of a relation file from `postgres` server.
@jesperpedersen  @Jubilee101 PTAL

[#709] Request a relation file from the postgres server

---

contrib/prometheus_scrape/README.md
contrib/prometheus_scrape/extra.info
contrib/prometheus_scrape/prometheus.py
doc/manual/en/10-prometheus.md

Added the scraping logic, ported from `pgexporter`.

[#745] Generate prometheus manual

---

src/include/utils.h
src/libpgmoneta/server.c
src/libpgmoneta/utils.c

The new workflow requires this util function a couple of times so I feel the need to incorporate it.
@jesperpedersen @Jubilee101 PTAL

[#753] Add a utils function to translate string lsn to integer lsn

---

src/include/walfile/wal_summary.h
src/libpgmoneta/walfile/wal_summary.c
test/testcases/test_wal_summary.c

Refactor #755 
@jesperpedersen @Jubilee101 PTAL

[#755] Refactor WAL Summarizer

---

doc/manual/en/80-server-api.md
src/include/server.h
src/libpgmoneta/server.c
test/include/tssuite.h
test/postgresql/src/postgresql17/conf/setup.sql
test/runner.c
test/testcases/test_server_api.c

feature: #758 
@jesperpedersen @Jubilee101 PTAL

[#758] Fetch metadata of a file from the postgres server

---

doc/CONFIGURATION.md
doc/DEVELOPERS.md
doc/WALFILTER.md
doc/man/pgmoneta-walfilter.1.rst
doc/manual/en/17-wal-tools.md
src/include/yaml_utils.h
src/libpgmoneta/walfile/wal_reader.c
src/libpgmoneta/yaml_utils.c
src/walfilter.c

This PR introduces filtering on XIDs as an additional filter, in addition to the DELETE filter. This imposed some modifications to the parser as well.

[#670] Implemented filtering on xid

---

doc/manual/en/80-server-api.md
src/include/server.h
src/libpgmoneta/server.c
test/testcases/test_server_api.c
test/testcases/test_wal_summary.c

Enhance: #722 
PTAl @jesperpedersen @Jubilee101

[#772] Extend  API to return current timeline ID
