pgmoneta/pgmoneta

- src/admin.c
- src/include/aes.h
- src/libpgmoneta/aes.c
- src/libpgmoneta/configuration.c
- src/libpgmoneta/security.c
Move aes features from security.h(c) to aes.h(c), fix correlated includes.
This commit bring no new feature to the codebase.
Refs: #56 #78
> refactor: move aes features to aes.h(c)

- src/include/memory.h
- src/include/message.h
- src/libpgmoneta/memory.c
- src/libpgmoneta/message.c
Finally, I resolved the bug (that was a stupid mistake)! This PR cosists of two functionalities:
One to read data from server into a buffer, it will left shift consumed data to reuse space, I tested locally and it was perfect, did not once exceed its original buffer size. For the sake of simplicity I just use the default buffer size (65535B), in the future we could have some configuration for the user to specify how big they want the stream buffer to be.
Another one is to parse data in the buffer, consume data into messages. It will block and return one message by another, and it will filter out those messages we are not interested in the stream replication process. And it will automatically read new data if current message is not complete.
I tested locally and it works perfectly, just as …
> [#123] Receive and consume copy stream messages

- src/include/message.h
- src/libpgmoneta/message.c
I had to re-implement this functionality similar to `pgmoneta_query_execute`. Because now all the data is in stream buffer. I also made some changes to `pgmoneta_consume_copy_stream` so that I can make use of existing APIs. I think it's better to submit this patch as a sperate PR because the next one (archive_streamer) should be really big and it'll take some time to finish.
> [#123] Receive and parse DataRow messages in stream buffer

- .github/workflows/ci.yml
- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- doc/ARCHITECTURE.md
- src/CMakeLists.txt
- src/include/achv.h
- src/include/message.h
- src/include/tablespace.h
- src/include/utils.h
- src/libpgmoneta/archive.c
- src/libpgmoneta/message.c
- src/libpgmoneta/server.c
- src/libpgmoneta/utils.c
- src/main.c
Finally! This is our native implementation of receiving and extracting the basebackup and the mainfest postgres server sends us. It uses libarchive to do the tar file extraction. We also support tablespaces now, for convenience I had to add the oid feild to the tablespace struct. So that I can keep track of and update the symbolic link easily. Let me know if you find it not ok. 
This implementation only works for server with version < 15, which sends tar file for each tablespaces separately. For server whose version >= 15, everything is sent in one backup stream so it's slightly different. 
I also have hesitations on whether to extract some parts into functions or if I'm putting the functionality in the right file. Feel free to give suggestions.
The correctness has be manually verified. …
> [#123] Receive and extract base backup archive

- contrib/grafana/dashboard.json
- src/include/utils.h
- src/libpgmoneta/prometheus.c
- src/libpgmoneta/utils.c
* pgmoneta_backup_version: The version of postgresql for a backup.
* pgmoneta_restore_size_increment: The size increment of a restore for a server.
* pgmoneta_backup_compression_ratio: The ratio of backup size to restore size for each backup.
> [#133] add backup metrics and design dashboard for them

- src/include/message.h
- src/include/utils.h
- src/libpgmoneta/message.c
- src/libpgmoneta/utils.c
- src/libpgmoneta/wal.c
ErrorResponse message usually consists of multiple fields, each with a type and a string, referring to https://www.postgresql.org/docs/current/protocol-error-fields.html.
Aside from the fields that tell you what the error is, postgres also tells you things like where in the source code the error was reported. It would be useful for debugging but messy and confusing for users. So I only log the "always present" fields (message, severity and error code) in ERROR level and leave the rest to DEBUG level.
At INFO level above, we shall see:
At DEBUG level, we'll see:
> [#158] extract and log CopyFail/ErrorResponse message

- src/include/message.h
- src/libpgmoneta/backup.c
- src/libpgmoneta/message.c
- src/libpgmoneta/wal.c
Sorry for the delay.. I tested it out and seems that after replacing the old pgmoneta_cosume_copy_stream, both wal and base backup are working fine. And we reduced a lot of mallocs:
> [#164] Reuse message buffer to hold consumed messages

- AUTHORS
- src/libpgmoneta/prometheus.c
Hi, 
In this PR, I have added the `atomic_bool backup` variable to the list of the variables exposed to Prometheus. 
With this addition, `pgmoneta_active_backup(name="XYZ") 1` in Prometheus metrics shows that a backup is currently ongoing on the "XYZ" instance. 
I could not find a testing mechanism in the repository to write tests for this functionality, but I have manually verified that the value is set to `1` correctly when a backup is in progress and otherwise, it's `0`. 
Would be happy to know your thoughts and comments on this :)
> Expose ongoing backup lock to prometheus as pgmoneta_active_backup

- src/include/pgmoneta.h
- src/include/wal.h
- src/libpgmoneta/bzip2_compression.c
- src/libpgmoneta/configuration.c
- src/libpgmoneta/gzip_compression.c
- src/libpgmoneta/lz4_compression.c
- src/libpgmoneta/prometheus.c
- src/libpgmoneta/wal.c
- src/libpgmoneta/zstandard_compression.c
Hi,
Sorry about the delay. This has been a crazy week 😩 
This patch provides us the ability to parse the history file. To make my life a little easier, I excluded .history file from being compressed - they are tiny anyway.
Prometheus is not making my life easy either, I cannot display hex string, nor put high and low 32 bits together, because it's A STRING!! So I display them separately in decimal for now. By default timeline 1 will have an invalid parent timeline of 0 and a switch point of 0/0.
Also spent great deal of time trying to connect local prometheus client to pgmoneta on Azure server. Turns out there's a firewall that overwrote Azure's inbound rules :(
Let me know if there's problem~
> [#187] Parse .history and expose to prometheus

- AUTHORS
- src/include/pgmoneta.h
- src/libpgmoneta/configuration.c
- src/libpgmoneta/prometheus.c
- src/libpgmoneta/wal.c
My steps for implementing a pgmoneta_current_wal_lsn are:
1. Create a new attribute pgmoneta_current_wal_lsn, which will be used to store xlogpos, in the struct server. (in pgmoneta.h file)
2. Every time xlogpos gets updated by pgmoneta_query_response_get_data function, its value will also get stored in pgmoneta_current_wal_lsn (in wal.c)
3. Append the WAL LSN of every server to Prometheus (in prometheus.c)
4. In the copy_server function, allow pgmoneta_current_wal_lsn to be copied from one server to another. (in configuration.c)
> [#207] Expose WAL log sequence number (pgmoneta_current_wal_lsn) to Prometheus

- src/include/restore.h
- src/include/utils.h
- src/include/workflow.h
- src/libpgmoneta/restore.c
- src/libpgmoneta/utils.c
- src/libpgmoneta/wf_restore.c
- src/libpgmoneta/workflow.c
Hi everyone!
This PR is addressing issue #216.
In this PR, I have defined a global variable named `excluded_files_names`, these files are ignored during the first round of restoring in the `pgmoneta_copy_postgresql` function. and I have defined a workflow named  `restore_excluded_files` and added it after the compression and restoring recovery files workflow. This ensures that files such as `pg_control` are restored only after the initial files are successfully decrypted, decompressed, and restored.
> [#216] Implement a mechanism to exclude some files in the first restore round

- AUTHORS
- src/include/info.h
- src/include/pgmoneta.h
- src/libpgmoneta/server.c
- src/libpgmoneta/wf_backup.c
I added a **MINOR_VERSION** label to record the minor version of the Postgres server in "backup.info" generated after making a full backup.
> [#221] Add a label of minor version in backup.info

- src/cli.c
- src/include/json.h
- src/include/management.h
- src/libpgmoneta/json.c
- src/libpgmoneta/management.c
Port the json functionality for command output from [pgagroal](https://github.com/agroal/pgagroal). Though a lot of local adaptations had to be made. Now `status`, `details`, `delete` and `list-backup` command support json format output.
> [#205] Add json format option for command output

- .gitignore
- doc/CONFIGURATION.md
- src/include/message.h
- src/include/pgmoneta.h
- src/include/utils.h
- src/libpgmoneta/configuration.c
- src/libpgmoneta/message.c
- src/libpgmoneta/utils.c
- src/libpgmoneta/wf_backup.c
This is just the first version of the rate limit. I have only implemented rate limiting for `pgmoneta_receive_archive_stream`, not for `pgmoneta_receive_archive_files`. 
What I want to make sure:
- This is the correct way to implement the limit.
- The code style is consistent with the rest of the file for integration.
Test Run:
- Successfully implemented backup rate limiting with no errors for now.
> [#197] Rate limit: Disk

- src/admin.c
This pull request enhances the master key validation process in the `master_key` function by adding warning messages.
Changes:
1. Modified the `is_valid_key` function to check for the following conditions:
- Key length hint
- Key cannot contain non-ASCII characters
Optional things could be done in the future:
- Max length of key, like 64 characters
- Key must contain at least one digit, one uppercase letter, one lowercase letter, and one symbol
> [#239] Add warning for illegal key while setting master-key manually

- src/main.c
To correct the logical error I replaced `j` with `follow`.
> [#250] Broken For loop

- src/include/info.h
- src/include/utils.h
- src/libpgmoneta/info.c
- src/libpgmoneta/prometheus.c
- src/libpgmoneta/utils.c
- src/libpgmoneta/wf_backup.c
I was investigating base backup on the server side and I realized I was ignoring starting/ending WAL position server sends us the whole time. So no need to look into the backup_label file for those info now. 
Also exposed the ending pos to prometheus, and fixed some minor bugs there as well.
> [#187] Receive WAL end pos of backup from server

- AUTHORS
- src/libpgmoneta/info.c
- src/libpgmoneta/prometheus.c
The backup.info can updated to add version number to it from the pgmoneta.h file.
example
VERSION = 0.10.0
> Adding PGMONETA_VERSION in backup.info Issue #235

- src/libpgmoneta/prometheus.c
Fix unclosed td tag in prometheus metric documentation
For discussion see: https://github.com/pgmoneta/pgmoneta/pull/240
> Fix unclosed td tag in prometheus metric documentation

- doc/manual/98-licenses.md
- doc/manual/99-references.md
- src/include/art.h
- src/include/deque.h
- src/include/link.h
- src/include/manifest.h
- src/include/utils.h
- src/libpgmoneta/aes.c
- src/libpgmoneta/art.c
- src/libpgmoneta/bzip2_compression.c
- src/libpgmoneta/deque.c
- src/libpgmoneta/gzip_compression.c
- src/libpgmoneta/link.c
- src/libpgmoneta/lz4_compression.c
- src/libpgmoneta/manifest.c
- src/libpgmoneta/se_hot_standby.c
- src/libpgmoneta/utils.c
- src/libpgmoneta/wf_link.c
- src/libpgmoneta/zstandard_compression.c
1. Implemented an adaptive radix tree for kv store
2. Use chunk loading during manifest comparison to ensure bounded memory usage
3. Use ART for quick insert/lookup during manifest comparison
4. Use manifest comparison instead of direct file comparison during link
5. Added a general deque for future usage
Currently our manifest comparison has a time complexity of O(ANlogk), supposing the manifests are of almost the same length, where A is the number of chunks inside manifest, N is number of entries inside manifest, and k being the length of the file path.
Usually the manifest fits in < 5 chunks or so, and k is bounded by maximum file path length, so the time complexity is near linear.
> Compare manifest in chunks using adaptive radix tree and iterative json parser

- src/include/csv.h
- src/include/pgmoneta.h
- src/include/security.h
- src/include/workflow.h
- src/libpgmoneta/bzip2_compression.c
- src/libpgmoneta/configuration.c
- src/libpgmoneta/csv.c
- src/libpgmoneta/gzip_compression.c
- src/libpgmoneta/link.c
- src/libpgmoneta/lz4_compression.c
- src/libpgmoneta/manifest.c
- src/libpgmoneta/message.c
- src/libpgmoneta/security.c
- src/libpgmoneta/wf_link.c
- src/libpgmoneta/wf_manifest.c
- src/libpgmoneta/workflow.c
- src/libpgmoneta/zstandard_compression.c
1. Convert backup_manifest from json format to simplified csv format named as backup.manifest. This is originally for extending the manifest from recording data directory only to also include tablespaces. Upon deeper investigation we found that the manifest includes tablespaces in the first place. But having a csv format manifest is still important for us, since in the future extension side will most likely build manifest as well, having a csv infrastructure is much easier and memory efficient than dealing with json directly.
2. Use the new manifest to link data and tablespaces directory.
3. Fix the bug that files are not linked correctly because of lack of compression suffix handling
New backup.manifest sits in the parent directory of data and tablespaces, the same as backup.info. This …
> [#316][#313] Link tablespaces with csv format manifest

- src/include/art.h
- src/include/csv.h
- src/include/deque.h
- src/include/json.h
- src/include/pgmoneta.h
- src/include/utils.h
- src/include/value.h
- src/include/verify.h
- src/libpgmoneta/archive.c
- src/libpgmoneta/art.c
- src/libpgmoneta/deque.c
- src/libpgmoneta/info.c
- src/libpgmoneta/json.c
- src/libpgmoneta/link.c
- src/libpgmoneta/management.c
- src/libpgmoneta/manifest.c
- src/libpgmoneta/restore.c
- src/libpgmoneta/se_ssh.c
- src/libpgmoneta/utils.c
- src/libpgmoneta/value.c
- src/libpgmoneta/verify.c
- src/libpgmoneta/wf_archive.c
- src/libpgmoneta/wf_backup.c
- src/libpgmoneta/wf_manifest.c
- src/libpgmoneta/wf_restore.c
- src/libpgmoneta/wf_verify.c
Add a universal typed `value` struct that can be shared across `ART`, `deque` and `json`. It has two callbacks - `to_string` for printing and `destroy_data` for memory reclaim. With all types (almost) equipped with to_string() method, logging is more clearer than ever before. The system is also easy to extend to include other types.
Redesign `deque` and `ART` on basis of `value` struct, which are now able to hold ANY type of values without the memory leak nightmare.
Redesign `json` on basis of `deque` and `json`, now able to put and look up a kv pair in O(k) time where k is the length of the key, and append an array entry in O(1) time, and, you guessed it, no worries about memory leak :)
Add iterator for `json` and `deque`.
> [#350] Universal value types

- src/cli.c
Add a new type for the unknown format type to restrict user input.
Also, add `(void)bytes_read;` to avoid the unused variable error.
> [#389] Add new type for unknown format type

- src/include/utils.h
- src/libpgmoneta/configuration.c
- src/libpgmoneta/se_azure.c
- src/libpgmoneta/security.c
- src/libpgmoneta/utils.c
Update the base64 encode and decode function signatures to make them more compatible with different data types.
> [#392] Correct the base64 functions signature

- AUTHORS
- doc/manual/97-acknowledgement.md
- doc/manual/advanced/97-acknowledgement.md
- src/include/configuration.h
- src/walinfo.c
When the config file is not provided then it will print warning on the console and also set `configuration_path` to the default value `/etc/pgmoneta/pgmoneta.conf` so that it is truly optional and that it don't throw and error down below when the system start actually using `configuration_path` (at line 273 or so)
This PR solves #475 
Kindly review. @jesperpedersen
> [#475] Make config argument optional and set default configuration path

- AUTHORS
- doc/GETTING_STARTED.md
- doc/man/pgmoneta-admin.1.rst
- doc/manual/97-acknowledgement.md
- doc/manual/advanced/03-installation.md
- doc/manual/advanced/97-acknowledgement.md
- doc/manual/user-01-quickstart.md
- doc/tutorial/01_install.md
- src/admin.c
Passing the password through the "--password" command line argument is potentially insecure, as the value would be exposed in a process listing or shell history. Read an environment variable as an alternative.
> admin: support password through environment

- src/admin.c
-Implemented a macro that automatically chooses getenv on Apple platforms and secure_getenv on other systems to ensure macOS compatibility
-fixes #502
> Use GET_ENV macro for environment variable

- src/include/backup.h
- src/include/restore.h
- src/include/workflow.h
- src/include/workflow_funcs.h
- src/libpgmoneta/backup.c
- src/libpgmoneta/restore.c
- src/libpgmoneta/wf_restore.c
- src/libpgmoneta/workflow.c
This should decrease our disk requirement for incremental backup combine drastically, now the overhead is only a chain of one file, instead of a chain of backups.
> File-by-file incremental backup combine

- doc/manual/97-acknowledgement.md
- doc/manual/advanced/05-backup.md
- doc/manual/advanced/97-acknowledgement.md
- doc/manual/user-10-cli.md
- src/cli.c
- src/include/management.h
- src/include/utils.h
- src/libpgmoneta/backup.c
- src/libpgmoneta/management.c
implement [#538](https://github.com/pgmoneta/pgmoneta/issues/538)
This PR adds a `--sort` option to the `list-backup` CLI command, allowing users to sort backups by time in either ascending (`asc`) or descending (`desc`) order. This enhancement improves usability by enabling easier inspection of backup history in the desired order.
Output:
```Header:
ClientVersion: 0.16.0
Command: list-backup
...
Response:
Backups:
- Backup: 20250330135708
BackupSize: 3.98MB
...
- Backup: 20250330105024
BackupSize: 3.98MB
...
- Backup: 20250330102835
BackupSize: 6.44MB
...
NumberOfBackups: 3
```
Output:
```
Header:
ClientVersion: 0.16.0
Command: list-backup
...
Response:
Backups:
- Backup: 20250330102835
BackupSize: 6.44MB
...
- Backup: 20250330105024
BackupSize: 3.98MB
...
- Backup: 20250330135708 …
```
> [#538] add --sort asc|desc option to list-backup command

- AUTHORS
- doc/manual/97-acknowledgement.md
- doc/manual/advanced/97-acknowledgement.md
- src/include/utils.h
- src/libpgmoneta/utils.c
implement #514
This PR introduces an enhanced stack backtrace feature that provides detailed debugging information, including function names, filenames, and line numbers. When `pgmoneta_backtrace` is called, it generates a formatted stack trace that is particularly useful for debugging and troubleshooting.
The following example demonstrates the output when `pgmoneta_backtrace` is invoked from the `version` function in `src/main.c:206`:
```
#0  0x7c00d33dff2a in pgmoneta_backtrace
at /home/silver/code/pgmoneta/src/libpgmoneta/utils.c:4543
#1  0x5dc62da7fe25 in version
at /home/silver/code/pgmoneta/src/main.c:206
#2  0x5dc62da7c1e0 in main
at /home/silver/code/pgmoneta/src/main.c:301
```
- The implementation leverages the [`libbacktrace`](https://github.com/ianlancetaylor/libbacktrace) to …
> [#514] Print line numbers in pgmoneta_backtrace

- src/include/workers.h
- src/libpgmoneta/workers.c
implement #557 
This PR replace the custom queue in `workers.c` with the existing deque in `deque.c` implementation.
1. The task is now included into `worker_common`, instead of being wrapped in a separate `struct task`. Since the deque is designed to hold generic values (with cleanup via value_config), storing the complete task in a single structure simplifies both insertion and memory management.
2. Move `struct semaphore* has_tasks;` from original queue to workers since deque doesn't have semaphore logic.
> [#557] Workers: Use Deque

- doc/CMakeLists.txt
New policy rules
https://cmake.org/cmake/help/latest/policy/CMP0175.html#policy:CMP0175
As per the new CMake policy CMP0175, I've updated the project to comply with the latest standards. The old policy is being deprecated and will soon be retired, so it’s important to transition to the new one
> [#600] Build: cmake 3.31+

- test/testsuite.sh
The recent postgres versions which are either the beta versions or the pre-release version have versioning something like `18devel` or `18beta1` . To parse the version and compare it with our requirement in testsuite, we read only the numeric part of the version string using regex.
`s/^([0-9]+(\.[0-9]+)?).*/\1/`.
Note: It will however drop the patch version.
@jesperpedersen PTAL
> [#623] test suite: Development servers

- src/include/http.h
- src/libpgmoneta/http.c
- src/libpgmoneta/se_azure.c
- src/libpgmoneta/se_s3.c
- test/testcases/pgmoneta_test_3.c
- test/tsclient_http.c
Backporting changes from `pgexporter` and updating test client to use a HTTP server created on a thread instead of relying on third party.
Apologies to anyone facing inconvenience with the test cases, I did not think postman will create a blockade when I first used it in test cases.
PTAL @jesperpedersen
> Update HTTP Suite

- src/libpgmoneta/server.c
Fix: #746 
Added an additional check for hex length, so if no data is received just return. This avoids calling the `malloc` which will then cause leaks.
@jesperpedersen @Jubilee101 PTAL
> [#746] Memory Leak while converting bytea to binary for a chunk not present
